---
- hosts: all
  become: yes
  vars_files:
  - external_vars.yml
  tasks:

  # install updates --------------------------------------------------------- #
  
  - name: Update kernel packages first
    apt:
      name: 'kernel*'
      state: latest
      update_cache: yes
      only_upgrade: yes
    register: apt_update_kernel

  - name: Update all installed packages
    apt:
      name: '*'
      state: latest
      update_cache: yes
      only_upgrade: yes

  - name: Remove packages not needed anymore
    apt:
      autoremove: yes


  # install new packages ---------------------------------------------------- #

  - name: install packages
    action: > 
      {{ ansible_pkg_mgr }} name="{{ pkgs }}" state=present update_cache=yes 


  # configure docker -------------------------------------------------------- #

  - name: Add Docker GPG apt Key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
  
  - name: Add Docker Repository
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu bionic stable
      state: present
  
  - name: Update apt and install docker-ce
    apt: update_cache=yes name=docker-ce state=latest
  
  - name: Install Docker Module for Python
    pip:
      name: docker
  
  - name: Allow local registry as insecure registry
    copy:
      dest: "/etc/docker/daemon.json"
      content: |
        {
            "insecure-registries" : ["localhost:32000"]
        }
  
  - name: Start docker service
    systemd:
      state: started
      name: docker


  # install microk8s -------------------------------------------------------- #

  - name: Install microk8s snap
    snap:
      name=microk8s
      classic=yes
      state=present
    register: microk8s

  - name: Start microk8s services
    ansible.builtin.shell: export LC_ALL=C.UTF-8 && \
      export LANG=C.UTF-8 && \
      microk8s enable "{{ microk8s_services }}"


  # create and configure ansible user --------------------------------------- #

  - name: Create user account and add user to groups sudo, microk8s, docker
    ansible.builtin.user:
      name: "{{ my_ansible_user }}"
      state: present
      shell: /bin/bash
      groups: sudo,docker,microk8s
      append: yes
    register: user_created
  
  - name: Allow 'sudo' group to have passwordless sudo
    ansible.builtin.lineinfile:
      dest: /etc/sudoers
      state: present
      regexp: '^%sudo'
      line: '%sudo ALL=(ALL) NOPASSWD: ALL'
      validate: 'visudo -cf %s'
    when: user_created.changed


  # configure ssh ----------------------------------------------------------- #

  - name: Set authorized key for user ansible by copying it from current user
    ansible.posix.authorized_key:
      user: "{{ my_ansible_user }}"
      state: present
      key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"

  - name: Deactivate root ssh login
    ansible.builtin.lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^PermitRootLogin'
      line: PermitRootLogin no
    register: sshd
  
  - name: Restart sshd service after disabling root ssh login
    ansible.builtin.service:
      name: sshd
      state: restarted
    when: sshd.changed


  # reboot after kernel update or microk8s installation --------------------- #

  - name: Reboot when kernel packages were updated or microk8s installed
    reboot:
      post_reboot_delay: 60
    when: apt_update_kernel.changed or microk8s.changed
