---
- hosts: all
  become: yes
  vars_files:
  - external_vars.yml
  tasks:

  - name: Update kernel packages first
    apt:
      name: 'kernel*'
      state: latest
      update_cache: yes
      only_upgrade: yes
    register: apt_update_kernel

  - name: Update all installed packages
    apt:
      name: '*'
      state: latest
      update_cache: yes
      only_upgrade: yes

  - name: Remove packages not needed anymore
    apt:
      autoremove: yes

  - name: Reboot when kernel packages were updated
    reboot:
      post_reboot_delay: 60
    when: apt_update_kernel.changed
